### ISSUE TITLE
Falta subir la carpeta public

### ISSUE THREAD

**Issue by ahmedglez** [MajorasBoi/Gamor-Platform#2]
Sin esta carpeta no se van a ver los archivos estaticos que tengas ahi: imagenes, iconos, fuentes, etc.
Tienes incluida la carpeta de public en el `.gitignore`, borrala de ahi

![Screenshot (6)](https://github.com/MajorasBoi/Gamor-Platform/assets/69789480/aada98d7-a521-45ee-9b46-6e0fb41f72f0)

**Comment by MajorasBoi** [comment]
Ya corregi el .gitignore
