### ISSUE TITLE
Estilos repetidos

### ISSUE THREAD

**Issue by ahmedglez** [MajorasBoi/Gamor-Platform#3]
Los estilos css es de los que mas organizacion deben tener porque funcionan en cascada y los estilos que definas en un componente padre tambien van a afectar a todos sus hijos. Te voy a ir dejando aqui algunas sugerencias:

1. En `src\components\MainLayout.css` tienes definido muchas veces `color: #c5c6c7`. Es mejor definirlo una unica vez en la clase del container y luego si quieres que un elemento en especifico no tenga ese color, lo sobrescribes. Anade esta clase justo debajo de la de `.main-container` y borra el resto de `color: #c5c6c7` que estan repetidos: 
`.main-container * {
    color: #c5c6c7;
}`

**Comment by ahmedglez** [comment]
2. Las clases CSS no hace falta que las pongas asi ` .main-container .container .header-section .time-container`, pudiendo poner simplemente `.time-container`. La manera en que lo estas usando tuviera sentido si tuvieses muchos elementos con esa clase y quisieras solamente afectar al que esta dentro de `.main-container .container .header-section`, pero no es el caso.

**Comment by MajorasBoi** [comment]
Hecho
