### ISSUE TITLE
Filtrado de Streamers

### ISSUE THREAD

**Issue by ahmedglez** [MajorasBoi/Gamor-Platform#4]
Para que te filtre tienes que anadirle al custom hook `src\hooks\useFilteredStreamers.ts` un valor por props que va a ser lo que introduzca el usuario en el buscador y un useEffect nuevo que cada vez que cambie ese valor, reaccione y filtre el array de nuevo. Te dejo por aqui como seria el useEffect, pero el resto te lo dejo a ti ;)

`  useEffect(() => {
    const filtered = streamers.filter((streamer: Streamer) => {
      return streamer.username.toLowerCase().includes(searchedValue.toLowerCase());
    })
    setFilteredStreamers(filtered)
  }, [searchedValue, streamers])`

Luego de que te funcione el filtrado anadele un renderizado condicional con un mensaje de "No results" o algo asi en caso de que el array de filtrados este vacio

**Comment by MajorasBoi** [comment]
Hecho
